export const TYPES = {
	INCREMENT: 'INCREMENT',
	INCREMENT_10: 'INCREMENT_10',
	DECREMENT: 'DECREMENT',
	DECREMENT_10: 'DECREMENT_10',
	MULTIPLY_2: 'MULTIPLY',
	MULTIPLY_5: 'MULTIPLY_5',
	DIVIDE_2: 'DIVIDE',
	DIVIDE_5: 'DIVIDE_5',
	RESET: 'RESET',
};
